FROM ubuntu
MAINTAINER Chris Wang "wftop1@126.com"
ENV REFRESHED_AT 20190122
#RUN sudo date -s "2019/01/22 09:00:00"
#RUN apt-get update -yqq && apt-get -yqq install ruby ruby-dev build-essential redis-tools
#RUN gem install --no-rdoc --no-ri sinatra json redis
#RUN mkdir -p /opt/webapp
EXPOSE 4567
CMD [ "/opt/webapp/bin/webapp" ]

