FROM centos
MAINTAINER Chris Wang "wftop1@gmail.com"
ENV REFESHED_AT 20190115
#RUN yum install epel-release -y
#RUN apt-get update -yqq && apt-get -yqq install ruby ruby-dev build-essential redis-tools
#RUN yum update -y && yum install ruby ruby-dev build-essential redis-tools which -y
#RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB 
#RUN curl -sSL https://get.rvm.io | bash -s stable
#RUN find / -name rvm -print
#RUN ruby --version
#RUN source /etc/profile.d/rvm.sh
#RUN source ~/.rvm/scripts/rvm
#RUN /usr/local/rvm/bin/rvm install 2.3.2 
#RUN /usr/local/rvm/bin/rvm use 2.3.2
#RUN /usr/local/rvm/bin/rvm remove 2.0.0
#RUN ruby --version
#RUN gem install rubygems-update update_rubygems
#RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
#RUN curl -sSL https://get.rvm.io | bash -s stable
#RUN /usr/local/rvm/bin/rvm install 2.4.1
#RUN /usr/local/rvm/bin/rvm use 2.4.1
#RUN /usr/local/rvm/bin/rvm remove 2.0.0
#RUN gem install --no-rdoc --no-ri sinatra json redis
#RUN mkdir -p /opt/webapp
EXPOSE 4567
#CMD [ "/opt/webapp/bin/webapp" ]
