FROM centos
MAINTAINER Chris Wang "wftop1@gmail.com"
ENV REFESHED_AT 20190115
RUN yum install epel-release -y
RUN yum install redis -y
#EXPOSE 6379
#ENTRYPOINT [ "/usr/bin/redis-server /etc/redis.conf" ]
#CMD []
